import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "node_modules",
      "coverage",
      "test-results",
      "reports",
      "allure-results",
      "allure-report",
      /* The html reporter bundles Playwright's own trace viewer here, browser code lint cannot read.
         A bare directory name does not match its contents, so the glob is required. */
      "**/playwright-report/**",
      /* Generated by bddgen on every run. */
      "**/.features-gen/**",
      /* The starting states the Playwright agents are handed. A fixture is activated by being
         declared, so the ones these files never read are the point rather than an oversight. */
      "**/tests/seeds/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: true }],
    },
  },
  {
    /* A test reaches the browser only through a page object. Scoped by glob rather than by
       exclusion, so the rule simply does not exist over `core`, the page objects, the fixtures,
       `features/support/` and `gitea-selenium-vitest/src/`, which are where these calls belong. */
    files: ["services/*/tests/**/*.ts", "services/*/features/step-definitions/**/*.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "MemberExpression[object.name='page'][property.name='locator']",
          message:
            "A spec does not build its own locators. Call the page object that owns this page, and add a method there when none fits.",
        },
        {
          selector: "MemberExpression[object.name='page'][property.name='goto']",
          message:
            "A spec does not navigate by URL. Call `open()` on the page object that owns this page.",
        },
        {
          selector: "MemberExpression[object.name='page'][property.name=/^getBy/]",
          message:
            "A spec does not build its own locators. Call the page object that owns this page, and add a method there when none fits.",
        },
        {
          selector: "MemberExpression[object.name='driver'][property.name=/^findElements?$/]",
          message:
            "A spec does not find its own elements. Call the page object that owns this page, and add a method there when none fits.",
        },
        {
          selector: "MemberExpression[object.name='driver'][property.name='wait']",
          message:
            "A spec does not wait on the driver. Use the page object's own wait, and when none fits add the wait to BaseComponent so every page gains it.",
        },
      ],
    },
  },
  {
    files: ["**/*.js", "**/*.mjs"],
    languageOptions: {
      globals: { process: "readonly", console: "readonly", fetch: "readonly", URL: "readonly" },
    },
    extends: [tseslint.configs.disableTypeChecked],
  },
  prettier,
);
